### PR TITLE
chore: add support to v16

### PR DESCRIPTION
**Pull request by RafaelGSS**
Address: https://github.com/clinicjs/node-clinic/issues/295

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by RafaelGSS** [comment]
The remaining tests I'm not able to reproduce locally. But looks like it's indeterministic since the creation.  https://github.com/clinicjs/node-clinic-doctor/actions

**Comment by RafaelGSS** [comment]
@mcollina Can I merge it or should look at the flaky windows tests?

**Comment by RafaelGSS** [comment]
Well, looks that https://github.com/clinicjs/node-clinic-doctor/pull/348/commits/ba904edd2d73a653c20a448417e0e503992bcaf0 fixes it.

Just for reference, it's needed because `tap@15` uses `node-preload` under the hood on windows paths: https://github.com/cfware/node-preload/blob/master/hook-spawn.js#L16. Similar behavior of: https://github.com/clinicjs/node-clinic-bubbleprof/pull/382#discussion_r744825479.

I'm a bit worried about that change on `tap@15`, changing the node environment under the hood is quite worrying. (`Jest` feeling)

**Pull request merged**
