### PR TITLE
chore: drop v12 support

### PR DESCRIPTION
**Pull request by RafaelGSS**

### CODE REVIEW

**Comment by RafaelGSS** [comment]
The scavenge process slightly changed in v18 (V8 update), so I'll work on that soon as I have time.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by RafaelGSS** [comment]
@mcollina Looks like the V8 updated how the `V8.Scavange` events are generated. AFAIK it's not documented anywhere, which is a constant problem when dealing with core libraries (specifically V8). The only content I found was: https://groups.google.com/g/v8-reviews/c/G3pNdydRhrU?pli=1.

Basically, the failing test is relying on something not reliable. At least, it's testing a `trace_event` value, which doesn't seem appropriate. It should only test if the file was generated successfully, regardless of the content. I will fix that in the next commit, but it clearly raised an issue for the Node.js Ecosystem.

How do we guarantee the V8 changes will not affect Node.js and user-land applications relying on _glue_ APIs such as `trace_events`? Is there any better place to discuss that? I've tried in the past to mention it in the Diagnostics WG but it got no traction.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
